development:
  adapter: postgresql
  encoding: unicode
  database: fullornot_development
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: fullornot_test
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: fullornot_production
  pool: 5
